language: node_js
node_js:
  - "0.10"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y python-software-properties curl build-essential git fontconfig"
  - "sudo add-apt-repository -y ppa:jon-severinsson/ffmpeg"
  - "sudo apt-get update"
  - "sudo apt-get install ffmpeg"

before_script:
  - "npm install -g bower"
  - "bower install"
  - "gulp build -o"
